### ISSUE TITLE
history* pattern

### ISSUE THREAD

**Issue by ingro** [KyleRoss/modclean#3]
Hello! Thanks for your script, I find it very useful especially now that I'm using it while building an Electron app. Anyway I have this small problem with the [React Router](https://github.com/rackt/react-router) library, since they have a file named `History.js`, and so after running `modclean` the entire app breaks.

I understand that "history" is a common name for changelog files, but could the rule be changed so it delete the file only if its extension is something different from `js`? Thank you.

**Comment by KyleRoss** [comment]
Thanks for reporting this, I will change the patterns to fix it.

**Comment by KyleRoss** [comment]
Fixed and published in version 1.2.2

**Comment by ingro** [comment]
Thank you sir :)

**Comment by DanielSundberg** [comment]
Still an issue for me in 1.2.7, see https://github.com/KyleRoss/modclean/issues/8

**Comment by McPo** [comment]
This is still an issue as React Router depends on the package history.
Should history just be moved to danger. As ReactRouter is a popular repo.
